# Official mirror list: https://www.gnu.org/prep/ftp.html
Timestamp: 2025-11-05

Primary: https://ftpmirror.gnu.org

afr-MA: http://mirror.marwan.ma/gnu
afr-MA: https://mirror.marwan.ma/gnu
afr-ZA: http://mirror.ufs.ac.za/gnu
afr-ZA: https://mirror.ufs.ac.za/gnu
asi-CN: http://mirrors.nju.edu.cn/gnu
asi-CN: http://mirrors.ustc.edu.cn/gnu
asi-CN: https://mirrors.nju.edu.cn/gnu
asi-CN: https://mirrors.tuna.tsinghua.edu.cn/gnu
asi-CN: https://mirrors.ustc.edu.cn/gnu
asi-IN: http://mirror.kumi.systems/gnu
asi-IN: http://mirrors.hopbox.net/gnu
asi-IN: https://mirror.kumi.systems/gnu
asi-IN: https://mirrors.hopbox.net/gnu
asi-JP: http://ftp.jaist.ac.jp/pub/GNU
asi-JP: https://ftp.jaist.ac.jp/pub/GNU
asi-KR: https://ftp.kaist.ac.kr/gnu
asi-TH: https://mirror.cyberbits.asia/gnu
asi-TW: http://mirror.ossplanet.net/gnu
asi-TW: http://mirror.twds.com.tw/gnu
asi-TW: https://mirror.ossplanet.net/gnu
asi-TW: https://mirror.twds.com.tw/gnu
aus-AU: https://mirrors.middlendian.com/gnu
aus-NC: http://mirror.lagoon.nc/gnu
aus-NC: https://mirror.lagoon.nc/gnu
eur-AT: ftp://mirror.easyname.at/gnu
eur-AT: http://mirror.easyname.at/gnu
eur-AT: https://mirror.easyname.at/gnu
eur-BG: ftp://sotirov-bg.net/pub/mirrors/gnu
eur-BG: https://ftp.sotirov-bg.net/pub/mirrors/gnu
eur-DE: ftp://mirror.checkdomain.de/gnu
eur-DE: ftp://mirror.netcologne.de/gnu
eur-DE: http://ftp-stud.hs-esslingen.de/pub/Mirrors/ftp.gnu.org
eur-DE: http://ftp.fau.de/gnu
eur-DE: http://ftp.halifax.rwth-aachen.de/gnu
eur-DE: http://mirror.checkdomain.de/gnu
eur-DE: http://mirror.dogado.de/gnu
eur-DE: http://mirror.netcologne.de/gnu
eur-DE: http://www.artfiles.org/gnu.org
eur-DE: https://ftp-stud.hs-esslingen.de/pub/Mirrors/ftp.gnu.org
eur-DE: https://ftp.fau.de/gnu
eur-DE: https://ftp.halifax.rwth-aachen.de/gnu
eur-DE: https://mirror.checkdomain.de/gnu
eur-DE: https://mirror.dogado.de/gnu
eur-DE: https://mirror.netcologne.de/gnu
eur-DE: https://www.artfiles.org/gnu.org
eur-DK: ftp://mirrors.dotsrc.org/gnu
eur-DK: http://ftp.klid.dk/ftp/gnu
eur-DK: http://mirrors.dotsrc.org/gnu
eur-DK: https://mirrors.dotsrc.org/gnu
eur-ES: http://ftp.rediris.es/mirror/GNU
eur-ES: https://ftp.rediris.es/mirror/GNU
eur-FI: ftp://ftp.funet.fi/pub/gnu/prep
eur-FI: http://www.nic.funet.fi/pub/gnu/ftp.gnu.org/pub/gnu
eur-FI: https://www.nic.funet.fi/pub/gnu/ftp.gnu.org/pub/gnu
eur-FR: http://mirror.ibcp.fr/pub/gnu
eur-FR: https://mirror.ibcp.fr/pub/gnu
eur-GR: ftp://ftp.cc.uoc.gr/mirrors/gnu
eur-GR: http://fosszone.csd.auth.gr/gnu
eur-GR: http://ftp.cc.uoc.gr/mirrors/gnu
eur-GR: https://fosszone.csd.auth.gr/gnu
eur-GR: https://ftp.cc.uoc.gr/mirrors/gnu
eur-HU: http://quantum-mirror.hu/mirrors/pub/gnu
eur-HU: https://quantum-mirror.hu/mirrors/pub/gnu
eur-MD: http://mirror.ihost.md/gnu
eur-MD: https://mirror.ihost.md/gnu
eur-NL: ftp://ftp.nluug.nl/pub/gnu
eur-NL: http://ftp.nluug.nl/pub/gnu
eur-NL: http://ftp.snt.utwente.nl/pub/software/gnu
eur-NL: https://ftp.nluug.nl/pub/gnu
eur-NL: https://ftp.snt.utwente.nl/pub/software/gnu
eur-NO: http://gnuftp.uib.no
eur-NO: https://gnuftp.uib.no
eur-PL: http://ftp.man.poznan.pl/gnu
eur-PL: http://sunsite.icm.edu.pl/pub/gnu
eur-PL: https://ftp.man.poznan.pl/gnu
eur-PL: https://sunsite.icm.edu.pl/pub/gnu
eur-PT: http://ftp.eq.uc.pt/software/unix/gnu
eur-PT: https://ftp.eq.uc.pt/software/unix/gnu
eur-RO: http://mirrors.nav.ro/gnu
eur-RO: https://mirrors.nav.ro/gnu
eur-RU: http://mirror.tochlab.net/pub/gnu
eur-RU: http://mirror.truenetwork.ru/gnu
eur-RU: https://mirror.tochlab.net/pub/gnu
eur-RU: https://mirror.truenetwork.ru/gnu
eur-SE: http://mirror.accum.se/mirror/gnu.org/gnu
eur-SE: https://mirror.accum.se/mirror/gnu.org/gnu
eur-UA: https://ftp-gnu-org.ip-connect.vn.ua
eur-UA: https://mirror.clientvps.com/gnu
eur-UK: ftp://www.mirrorservice.org/sites/ftp.gnu.org/gnu
eur-UK: http://mirror.cyberbits.eu/gnu
eur-UK: https://mirror.cyberbits.eu/gnu
nam-CA: ftp://mirror.csclub.uwaterloo.ca/gnu
nam-CA: http://mirror.csclub.uwaterloo.ca/gnu
nam-CA: http://mirror.its.dal.ca/gnu
nam-CA: https://mirror.csclub.uwaterloo.ca/gnu
nam-CA: https://mirror.its.dal.ca/gnu
nam-US: ftp://mirror.keystealth.org/gnu
nam-US: http://ftp.gnu.org/gnu
nam-US: http://ftp.wayne.edu/gnu
nam-US: http://gnu.mirror.constant.com
nam-US: http://mirror.bahnhof.net/pub/gnu
nam-US: http://mirror.freedif.org/GNU
nam-US: http://mirror.keystealth.org/gnu
nam-US: http://mirror.lyrahosting.com/gnu
nam-US: http://mirror.rit.edu/gnu
nam-US: http://mirror.team-cymru.com/gnu
nam-US: http://mirror.us-midwest-1.nexcess.net/gnu
nam-US: http://mirrors.ibiblio.org/gnu
nam-US: http://mirrors.ocf.berkeley.edu/gnu
nam-US: http://www.gutscheinrausch.de/mirror/gnu
nam-US: https://ftp.gnu.org/gnu
nam-US: https://ftp.wayne.edu/gnu
nam-US: https://ftpmirror.gnu.org
nam-US: https://ftpmirror.gnu.org
nam-US: https://gnu.mirror.constant.com
nam-US: https://mirror.bahnhof.net/pub/gnu
nam-US: https://mirror.cs.odu.edu/gnu
nam-US: https://mirror.freedif.org/GNU
nam-US: https://mirror.lyrahosting.com/gnu
nam-US: https://mirror.team-cymru.com/gnu
nam-US: https://mirror.us-midwest-1.nexcess.net/gnu
nam-US: https://mirrors.ibiblio.org/gnu
nam-US: https://mirrors.ocf.berkeley.edu/gnu
nam-US: https://www.gutscheinrausch.de/mirror/gnu
sam-BR: http://gnu.c3sl.ufpr.br/ftp
sam-BR: https://gnu.c3sl.ufpr.br/ftp
sam-EC: https://mirror.cedia.org.ec/gnu
