# Official mirror list: https://www.gnu.org/prep/ftp.html
Timestamp: 2020-12-12

Primary: https://ftpmirror.gnu.org

afr-MA: http://mirror.marwan.ma/gnu
afr-MA: https://mirror.marwan.ma/gnu
afr-NA: http://download.nust.na/pub/ftp.gnu.org/gnu
afr-ZA: http://mirror.ufs.ac.za/gnu
asi-CN: http://mirrors.nju.edu.cn/gnu
asi-CN: http://mirrors.ustc.edu.cn/gnu
asi-CN: https://mirrors.nju.edu.cn/gnu
asi-CN: https://mirrors.sjtug.sjtu.edu.cn/gnu
asi-CN: https://mirrors.tuna.tsinghua.edu.cn/gnu
asi-CN: https://mirrors.ustc.edu.cn/gnu
asi-IN: https://de.freedif.org/gnu
asi-IR: http://mirror.rasanegar.com/gnu
asi-IR: https://mirror.rasanegar.com/gnu
asi-JP: ftp://mirror.jre655.com/GNU
asi-JP: http://ftp.jaist.ac.jp/pub/GNU
asi-JP: https://ftp.jaist.ac.jp/pub/GNU
asi-JP: https://mirror.jre655.com/GNU
asi-OM: http://mirror.squ.edu.om/gnu
asi-SA: http://mirror.lyrahosting.com/gnu
asi-SA: https://mirror.lyrahosting.com/gnu
asi-TW: http://mirror.ossplanet.net/gnu
asi-TW: https://mirror.ossplanet.net/gnu
asi-VN: http://mirror.freedif.org/GNU
asi-VN: https://mirror.freedif.org/GNU
aus-NC: http://mirror.lagoon.nc/gnu
eur-AT: ftp://mirror.easyname.at/gnu
eur-AT: ftp://mirror.inode.at/gnu
eur-AT: http://mirror.easyname.at/gnu
eur-AT: http://mirror.inode.at/gnu
eur-AT: https://mirror.easyname.at/gnu
eur-BG: ftp://sotirov-bg.net/pub/mirrors/gnu
eur-BG: https://ftp.sotirov-bg.net/pub/mirrors/gnu
eur-DE: ftp://mirror.checkdomain.de/gnu
eur-DE: ftp://mirror.netcologne.de/gnu
eur-DE: http://ftp-stud.hs-esslingen.de/pub/Mirrors/ftp.gnu.org
eur-DE: http://ftp.fau.de/gnu
eur-DE: http://ftp.halifax.rwth-aachen.de/gnu
eur-DE: http://ftp.hosteurope.de/mirror/ftp.gnu.org/gnu
eur-DE: http://ftp.wrz.de/pub/gnu
eur-DE: http://mirror.bibleonline.ru/gnu
eur-DE: http://mirror.checkdomain.de/gnu
eur-DE: http://mirror.clientvps.com/gnu
eur-DE: http://mirror.dogado.de/gnu
eur-DE: http://mirror.netcologne.de/gnu
eur-DE: http://www.artfiles.org/gnu.org
eur-DE: http://www.gutscheinrausch.de/mirror/gnu
eur-DE: http://www.singleboersen.com/mirror/gnu
eur-DE: https://ftp-stud.hs-esslingen.de/pub/Mirrors/ftp.gnu.org
eur-DE: https://ftp.fau.de/gnu
eur-DE: https://ftp.halifax.rwth-aachen.de/gnu
eur-DE: https://ftp.wrz.de/pub/gnu
eur-DE: https://mirror.bibleonline.ru/gnu
eur-DE: https://mirror.checkdomain.de/gnu
eur-DE: https://mirror.clientvps.com/gnu
eur-DE: https://mirror.dogado.de/gnu
eur-DE: https://mirror.netcologne.de/gnu
eur-DE: https://www.artfiles.org/gnu.org
eur-DE: https://www.gutscheinrausch.de/mirror/gnu
eur-DE: https://www.singleboersen.com/mirror/gnu
eur-DK: ftp://mirrors.dotsrc.org/gnu
eur-DK: http://ftp.download-by.net/gnu/gnu
eur-DK: http://mirrors.dotsrc.org/gnu
eur-DK: https://mirrors.dotsrc.org/gnu
eur-ES: http://ftp.rediris.es/mirror/GNU
eur-ES: https://ftp.rediris.es/mirror/GNU
eur-FI: ftp://ftp.funet.fi/pub/gnu/prep
eur-FI: https://www.nic.funet.fi/pub/gnu/ftp.gnu.org/pub/gnu
eur-FR: ftp://ftp.igh.cnrs.fr/pub/gnu
eur-FR: http://ftp-gnu-org.ip-connect.vn.ua
eur-FR: http://ftp.igh.cnrs.fr/pub/gnu
eur-FR: http://mirror.cyberbits.eu/gnu
eur-FR: http://mirror.ibcp.fr/pub/gnu
eur-FR: https://ftp-gnu-org.ip-connect.vn.ua
eur-FR: https://ftp.igh.cnrs.fr/pub/gnu
eur-FR: https://mirror.cyberbits.eu/gnu
eur-FR: https://mirror.ibcp.fr/pub/gnu
eur-GR: ftp://ftp.cc.uoc.gr/mirrors/gnu
eur-GR: ftp://ftp.ntua.gr/pub/gnu
eur-GR: http://ftp.cc.uoc.gr/mirrors/gnu
eur-GR: http://ftp.ntua.gr/pub/gnu
eur-GR: https://ftp.cc.uoc.gr/mirrors/gnu
eur-HU: http://quantum-mirror.hu/mirrors/pub/gnu
eur-HU: https://quantum-mirror.hu/mirrors/pub/gnu
eur-NL: ftp://ftp.mirror.nl/pub/mirror/gnu
eur-NL: ftp://ftp.nluug.nl/pub/gnu
eur-NL: http://ftp.snt.utwente.nl/pub/software/gnu
eur-NL: https://ftp.nluug.nl/pub/gnu
eur-NL: https://ftp.snt.utwente.nl/pub/software/gnu
eur-NO: http://gnuftp.uib.no
eur-NO: https://gnuftp.uib.no
eur-PL: ftp://ftp.man.poznan.pl/pub/gnu
eur-PL: ftp://ftp.task.gda.pl/pub/gnu
eur-PL: ftp://sunsite.icm.edu.pl/pub/gnu
eur-PL: http://ftp.task.gda.pl/pub/gnu
eur-PL: https://ftp.task.gda.pl/pub/gnu
eur-PL: https://sunsite.icm.edu.pl/pub/gnu
eur-PT: ftp://ftp.eq.uc.pt/pub/software/unix/gnu
eur-PT: ftp://mirrors.up.pt/pub/gnu
eur-PT: http://ftp.eq.uc.pt/software/unix/gnu
eur-PT: http://mirrors.up.pt/pub/gnu
eur-PT: https://ftp.eq.uc.pt/software/unix/gnu
eur-PT: https://mirrors.up.pt/pub/gnu
eur-RO: http://mirrors.nav.ro/gnu
eur-RO: https://mirrors.nav.ro/gnu
eur-RS: ftp://mirror.sbb.rs/gnu
eur-RS: http://mirror.sbb.rs/gnu
eur-RU: ftp://mirror.tochlab.net/pub/gnu
eur-RU: http://mirror.tochlab.net/pub/gnu
eur-RU: https://mirror.tochlab.net/pub/gnu
eur-SE: http://ftp.acc.umu.se/mirror/gnu.org/gnu
eur-SE: https://ftp.acc.umu.se/mirror/gnu.org/gnu
eur-TR: http://mirror.rackdc.com/gnu
eur-TR: http://mirror.veriportal.com/gnu
eur-UA: ftp://ftp.gnu.org.ua/gnu
eur-UA: http://ftp.gnu.org.ua/gnu
eur-UA: http://mirror.kumi.systems/gnu
eur-UA: https://ftp.gnu.org.ua/gnu
eur-UA: https://mirror.kumi.systems/gnu
eur-UK: ftp://www.mirrorservice.org/sites/ftp.gnu.org/gnu
eur-UK: http://mirrors.gethosted.online/gnu
eur-UK: http://www.mirrorservice.org/sites/ftp.gnu.org/gnu
eur-UK: https://mirrors.gethosted.online/gnu
eur-UK: https://www.mirrorservice.org/sites/ftp.gnu.org/gnu
nam-CA: ftp://gnu.mirror.iweb.com
nam-CA: ftp://mirror.csclub.uwaterloo.ca/gnu
nam-CA: http://gnu.mirror.iweb.com
nam-CA: http://mirror.csclub.uwaterloo.ca/gnu
nam-CA: http://mirror.its.dal.ca/gnu
nam-CA: http://mirrors.aliyun.com/gnu
nam-CA: https://mirror.csclub.uwaterloo.ca/gnu
nam-CA: https://mirrors.aliyun.com/gnu
nam-US: ftp://mirror.keystealth.org/gnu
nam-US: ftp://mirror.sergal.org/gnu
nam-US: ftp://mirrors.syringanetworks.net/gnu
nam-US: http://ftp.wayne.edu/gnu
nam-US: http://gnu.askapache.com
nam-US: http://gnu.freemirror.org/gnu
nam-US: http://gnu.mirror.constant.com
nam-US: http://gnu.mirrors.hoobly.com
nam-US: http://gnu.spinellicreations.com
nam-US: http://mirror-hk.koddos.net/gnu
nam-US: http://mirror.keystealth.org/gnu
nam-US: http://mirror.rit.edu/gnu
nam-US: http://mirror.sergal.org/gnu
nam-US: http://mirror.serverion.com/gnu
nam-US: http://mirror.team-cymru.com/gnu
nam-US: http://mirror.us-midwest-1.nexcess.net/gnu
nam-US: http://mirror.yongbok.net/gnu
nam-US: http://mirror2.evolution-host.com/gnu
nam-US: http://mirrors.ibiblio.org/pub/mirrors/gnu/ftp/gnu
nam-US: http://mirrors.kernel.org/gnu
nam-US: http://mirrors.mivocloud.com/gnu
nam-US: http://mirrors.ocf.berkeley.edu/gnu
nam-US: http://mirrors.syringanetworks.net/gnu
nam-US: https://ftp.wayne.edu/gnu
nam-US: https://ftpmirror.gnu.org
nam-US: https://gnu.askapache.com
nam-US: https://gnu.freemirror.org/gnu
nam-US: https://mirror-hk.koddos.net/gnu
nam-US: https://mirror.sergal.org/gnu
nam-US: https://mirror.serverion.com/gnu
nam-US: https://mirror.us-midwest-1.nexcess.net/gnu
nam-US: https://mirror.yongbok.net/gnu
nam-US: https://mirror2.evolution-host.com/gnu
nam-US: https://mirrors.kernel.org/gnu
nam-US: https://mirrors.mivocloud.com/gnu
nam-US: https://mirrors.ocf.berkeley.edu/gnu
nam-US: https://mirrors.sarata.com/gnu
nam-US: https://mirrors.syringanetworks.net/gnu
nam-US: https://mirrors.tripadvisor.com/gnu
sam-BR: http://gnu.c3sl.ufpr.br/ftp
sam-BR: http://mirror.nbtelecom.com.br/gnu
sam-BR: https://mirror.nbtelecom.com.br/gnu
sam-BZ: http://mirror.koddos.net/gnu
sam-BZ: https://mirror.koddos.net/gnu
sam-EC: http://mirror.cedia.org.ec/gnu
sam-EC: https://mirror.cedia.org.ec/gnu
